//
//  CountriesAndCapitals.swift
//  SimpleGames
//
//  Created by user on 27.04.2023.
//

import Foundation

struct CountryCapital: Identifiable {
    let id = UUID()
    let country: String
    let capital: String
}

class CountriesAndCapitals {

let countryAndCapital: [CountryCapital] =

  [
  CountryCapital(country: NSLocalizedString("Uruguay", comment: ""), capital: NSLocalizedString("Montevideo", comment: "")),
  CountryCapital(country: NSLocalizedString("Federated States of Micronesia", comment: ""), capital: NSLocalizedString("Palikir", comment: "")),
  CountryCapital(country: NSLocalizedString("Fiji", comment: ""), capital: NSLocalizedString("Suva", comment: "")),
  CountryCapital(country: NSLocalizedString("Philippines", comment: ""), capital: NSLocalizedString("Manila", comment: "")),
  CountryCapital(country: NSLocalizedString("Finland", comment: ""), capital: NSLocalizedString("Helsinki", comment: "")),
  CountryCapital(country: NSLocalizedString("France", comment: ""), capital: NSLocalizedString("Paris", comment: "")),
  CountryCapital(country: NSLocalizedString("Croatia", comment: ""), capital: NSLocalizedString("Zagreb", comment: "")),
  CountryCapital(country: NSLocalizedString("Central African Republic", comment: ""), capital: NSLocalizedString("Bangui", comment: "")),
  CountryCapital(country: NSLocalizedString("Chad", comment: ""), capital: NSLocalizedString("N'Djamena", comment: "")),
  CountryCapital(country: NSLocalizedString("Montenegro", comment: ""), capital: NSLocalizedString("Podgorica", comment: "")),
  CountryCapital(country: NSLocalizedString("Czechia", comment: ""), capital: NSLocalizedString("Prague", comment: "")),
  CountryCapital(country: NSLocalizedString("Chile", comment: ""), capital: NSLocalizedString("Santiago", comment: "")),
  CountryCapital(country: NSLocalizedString("Switzerland", comment: ""), capital: NSLocalizedString("Bern", comment: "")),
  CountryCapital(country: NSLocalizedString("Sweden", comment: ""), capital: NSLocalizedString("Stockholm", comment: "")),
  CountryCapital(country: NSLocalizedString("Sri Lanka", comment: ""), capital: NSLocalizedString("Sri Jayawardenepura Kotte", comment: "")),
  CountryCapital(country: NSLocalizedString("Ecuador", comment: ""), capital: NSLocalizedString("Quito", comment: "")),
  CountryCapital(country: NSLocalizedString("Equatorial Guinea", comment: ""), capital: NSLocalizedString("Malabo", comment: "")),
  CountryCapital(country: NSLocalizedString("Eritrea", comment: ""), capital: NSLocalizedString("Asmara", comment: "")),
  CountryCapital(country: NSLocalizedString("Estonia", comment: ""), capital: NSLocalizedString("Tallinn", comment: "")),
  CountryCapital(country: NSLocalizedString("Ethiopia", comment: ""), capital: NSLocalizedString("Addis Ababa", comment: "")),
  CountryCapital(country: NSLocalizedString("South Africa", comment: ""), capital: NSLocalizedString("Pretoria", comment: "")),
  CountryCapital(country: NSLocalizedString("South Sudan", comment: ""), capital: NSLocalizedString("Juba", comment: "")),
  CountryCapital(country: NSLocalizedString("Jamaica", comment: ""), capital: NSLocalizedString("Kingston", comment: "")),
  CountryCapital(country: NSLocalizedString("Japan", comment: ""), capital: NSLocalizedString("Tokyo", comment: "")),
  CountryCapital(country: NSLocalizedString("Palestine", comment: ""), capital: NSLocalizedString("Jerusalem", comment: ""))
  ]

var dictionary = [
  "Австралия": "Канберра",
  "Андорра": "Андорра-ла-Велья",
  "Австрия": "Вена",
  "Азербайджан": "Баку",
  "Албания": "Тирана",
  "Алжир": "Алжир",
  "Ангола": "Луанда",
  "Аргентина": "Буэнос-Айрес",
  "Армения": "Ереван",
  "Афганистан": "Кабул",
  "Багамские Острова": "Нассау",
  "Бангладеш": "Дакка",
  "Барбадос": "Бриджтаун",
  "Бахрейн": "Манама",
  "Белиз": "Бельмопан",
  "Беларусь": "Минск",
  "Бельгия": "Брюссель",
  "Бенин": "Порто-Ново",
  "Болгария": "София",
  "Боливия": "Ла-Пас",
  "Босния и Герцеговина": "Сараево",
  "Ботсвана": "Габороне",
  "Бразилия": "Бразилиа",
  "Бруней": "Бандар-Сери-Бегаван",
  "Буркина-Фасо": "Уагадугу",
  "Бурунди": "Бужумбура",
  "Бутан": "Тхимпху",
  "Вануату": "Порт-Вила",
  "Великобритания": "Лондон",
  "Венгрия": "Будапешт",
  "Венесуэла": "Каракас",
  "Восточный Тимор": "Дили",
  "Вьетнам": "Ханой",
  "Габон": "Либревиль",
  "Гаити": "Порт-о-Пренс",
  "Гайана": "Джорджтаун",
  "Гамбия": "Банжул",
  "Гана": "Аккра",
  "Гватемала": "Гватемала",
  "Гвинея": "Конакри",
  "Гвинея-Бисау": "Бисау",
  "Германия": "Берлин",
  "Гондурас": "Тегусигальпа",
  "Гренада": "Сент-Джорджес",
  "Греция": "Афины",
  "Грузия": "Тбилиси",
  "Дания": "Копенгаген",
  "Демократическая Республика Конго": "Киншаса",
  "Джибути": "Джибути",
  "Доминика": "Розо",
  "Доминиканская Республика": "Санто-Доминго",
  "Египет": "Каир",
  "Замбия": "Лусака",
  "Зимбабве": "Хараре",
  "Израиль": "Иерусалим",
  "Индия": "Нью-Дели",
  "Индонезия": "Джакарта",
  "Иордания": "Амман",
  "Ирак": "Багдад",
  "Ирландия": "Дублин",
  "Исландия": "Рейкьявик",
  "Испания": "Мадрид",
  "Италия": "Рим",
  "Йемен": "Сана",
  "Кабо-Верде": "Прая",
  "Казахстан": "Нур-Султан",
  "Камбоджа": "Пномпень",
  "Камерун": "Яунде",
  "Канада": "Оттава",
  "Катар": "Доха",
  "Кения": "Найроби",
  "Киргизия": "Бишкек",
  "Китай": "Пекин",
  "Колумбия": "Богота",
  "Коморы": "Морони",
  "Коста-Рика": "Сан-Хосе",
  "Кот-д’Ивуар": "Ямусукро",
  "Куба": "Гавана",
  "Кувейт": "Эль-Кувейт",
  "Лаос": "Вьентьян",
  "Латвия": "Рига",
  "Ливия": "Триполи",
  "Литва": "Вильнюс",
  "Люксембург": "Люксембург",
  "Маврикий": "Порт-Луи",
  "Мавритания": "Нуакшот",
  "Мадагаскар": "Антананариву",
  "Македония": "Скопье",
  "Малайзия": "Куала-Лумпур",
  "Мали": "Бамако",
  "Мальдивы": "Мале",
  "Мальта": "Валлетта",
  "Марокко": "Рабат",
  "Мексика": "Мехико",
  "Мозамбик": "Мапуту",
  "Молдавия": "Кишинёв",
  "Монако": "Монако",
  "Монголия": "Улан-Батор",
  "Мьянма": "Найпьидо",
  "Намибия": "Виндхук",
  "Нигер": "Ниамей",
  "Нигерия": "Абуджа",
  "Нидерланды": "Амстердам",
  "Никарагуа": "Манагуа",
  "Новая Зеландия": "Веллингтон",
  "Норвегия": "Осло",
  "Объединенные Арабские Эмираты": "Абу-Даби",
  "Оман": "Маскат",
  "Пакистан": "Исламабад",
  "Палау": "Нгерулмуд",
  "Панама": "Панама",
  "Папуа — Новая Гвинея": "Порт-Морсби",
  "Парагвай": "Асунсьон",
  "Перу": "Лима",
  "Польша": "Варшава",
  "Португалия": "Лиссабон",
  "Республика Кипр": "Никосия",
  "Республика Конго": "Браззавиль",
  "Республика Корея": "Сеул",
  "Республика Косово": "Приштина",
  "Россия": "Москва",
  "Руанда": "Кигали",
  "Румыния": "Бухарест",
  "США": "Вашингтон",
  "Сальвадор": "Сан-Сальвадор",
  "Самоа": "Апиа",
  "Сан-Марино": "Сан-Марино",
  "Сан-Томе и Принсипи": "Сан-Томе",
  "Саудовская Аравия": "Эр-Рияд",
  "Свазиленд": "Мбабане",
  "Северная Корея": "Пхеньян",
  "Сейшельские Острова": "Виктория",
  "Сенегал": "Дакар",
  "Сент-Винсент и Гренадины": "Кингстаун",
  "Сент-Китс и Невис": "Бастер",
  "Сент-Люсия": "Кастри",
  "Сербия": "Белград",
  "Сингапур": "Сингапур",
  "Сирия": "Дамаск",
  "Словакия": "Братислава",
  "Словения": "Любляна",
  "Соломоновы Острова": "Хониара",
  "Сомали": "Могадишо",
  "Судан": "Хартум",
  "Суринам": "Парамарибо",
  "Сьерра-Леоне": "Фритаун",
  "Таджикистан": "Душанбе",
  "Таиланд": "Бангкок",
  "Танзания": "Додома",
  "Того": "Ломе",
  "Тонга": "Нукуалофа",
  "Тринидад и Тобаго": "Порт-оф-Спейн",
  "Тунис": "Тунис",
  "Туркменистан": "Ашхабад",
  "Турция": "Анкара",
  "Уганда": "Кампала",
  "Узбекистан": "Ташкент",
  "Украина": "Киев",
  "Уругвай": "Монтевидео",
  "Федеративные Штаты Микронезии": "Паликир",
  "Фиджи": "Сува",
  "Филиппины": "Манила",
  "Финляндия": "Хельсинки",
  "Франция": "Париж",
  "Хорватия": "Загреб",
  "Центральноафриканская Республика": "Банги",
  "Чад": "Загреб",
  "Черногория": "Банги",
  "Чехия": "Прага",
  "Чили": "Сантьяго",
  "Швейцария": "Берн",
  "Швеция": "Стокгольм",
  "Шри-Ланка": "Шри-Джаяварденепура-Котте",
  "Эквадор": "Кито",
  "Экваториальная Гвинея": "Малабо",
  "Эритрея": "Асмэра",
  "Эстония": "Таллин",
  "Эфиопия": "Аддис-Абеба",
  "Южно-Африканская Республика": "Претория",
  "Южный Судан": "Джуба",
  "Ямайка": "Кингстон",
  "Япония": "Токио",
  "Палестина": "Иерусалим"
]
}
