//
//  CountriesAndCapitals.swift
//  SimpleGames
//
//  Created by user on 27.04.2023.
//

import Foundation

struct CountryCapital: Identifiable {
    let id = UUID()
    let country: String
    let capital: String
}

class CountriesAndCapitals {

let countryAndCapital: [CountryCapital] =

  [
  CountryCapital(country: NSLocalizedString("Uruguay", comment: ""), capital: NSLocalizedString("Montevideo", comment: "")),
  CountryCapital(country: NSLocalizedString("Federated States of Micronesia", comment: ""), capital: NSLocalizedString("Palikir", comment: "")),
  CountryCapital(country: NSLocalizedString("Fiji", comment: ""), capital: NSLocalizedString("Suva", comment: "")),
  CountryCapital(country: NSLocalizedString("Philippines", comment: ""), capital: NSLocalizedString("Manila", comment: "")),
  CountryCapital(country: NSLocalizedString("Finland", comment: ""), capital: NSLocalizedString("Helsinki", comment: "")),
  CountryCapital(country: NSLocalizedString("France", comment: ""), capital: NSLocalizedString("Paris", comment: "")),
  CountryCapital(country: NSLocalizedString("Croatia", comment: ""), capital: NSLocalizedString("Zagreb", comment: "")),
  CountryCapital(country: NSLocalizedString("Central African Republic", comment: ""), capital: NSLocalizedString("Bangui", comment: "")),
  CountryCapital(country: NSLocalizedString("Chad", comment: ""), capital: NSLocalizedString("N'Djamena", comment: "")),
  CountryCapital(country: NSLocalizedString("Montenegro", comment: ""), capital: NSLocalizedString("Podgorica", comment: "")),
  CountryCapital(country: NSLocalizedString("Czechia", comment: ""), capital: NSLocalizedString("Prague", comment: "")),
  CountryCapital(country: NSLocalizedString("Chile", comment: ""), capital: NSLocalizedString("Santiago", comment: "")),
  CountryCapital(country: NSLocalizedString("Switzerland", comment: ""), capital: NSLocalizedString("Bern", comment: "")),
  CountryCapital(country: NSLocalizedString("Sweden", comment: ""), capital: NSLocalizedString("Stockholm", comment: "")),
  CountryCapital(country: NSLocalizedString("Sri Lanka", comment: ""), capital: NSLocalizedString("Sri Jayawardenepura Kotte", comment: "")),
  CountryCapital(country: NSLocalizedString("Ecuador", comment: ""), capital: NSLocalizedString("Quito", comment: "")),
  CountryCapital(country: NSLocalizedString("Equatorial Guinea", comment: ""), capital: NSLocalizedString("Malabo", comment: "")),
  CountryCapital(country: NSLocalizedString("Eritrea", comment: ""), capital: NSLocalizedString("Asmara", comment: "")),
  CountryCapital(country: NSLocalizedString("Estonia", comment: ""), capital: NSLocalizedString("Tallinn", comment: "")),
  CountryCapital(country: NSLocalizedString("Ethiopia", comment: ""), capital: NSLocalizedString("Addis Ababa", comment: "")),
  CountryCapital(country: NSLocalizedString("South Africa", comment: ""), capital: NSLocalizedString("Pretoria", comment: "")),
  CountryCapital(country: NSLocalizedString("South Sudan", comment: ""), capital: NSLocalizedString("Juba", comment: "")),
  CountryCapital(country: NSLocalizedString("Jamaica", comment: ""), capital: NSLocalizedString("Kingston", comment: "")),
  CountryCapital(country: NSLocalizedString("Japan", comment: ""), capital: NSLocalizedString("Tokyo", comment: "")),
  CountryCapital(country: NSLocalizedString("Palestine", comment: ""), capital: NSLocalizedString("Jerusalem", comment: ""))
  ]

var dictionary = [
  "Австралия": "Канберра",
  "Андорра": "Андорра-ла-Велья",
  "Австрия": "Вена",
  "Азербайджан": "Баку",
  "Албания": "Тирана",
  "Алжир": "Алжир",
  "Ангола": "Луанда",
  "Аргентина": "Буэнос-Айрес",
  "Армения": "Ереван",
  "Афганистан": "Кабул",
  "Багамские Острова": "Нассау",
  "Бангладеш": "Дакка",
  "Барбадос": "Бриджтаун",
  "Бахрейн": "Манама",
  "Белиз": "Бельмопан",
  "Беларусь": "Минск",
  "Бельгия": "Брюссель",
  "Бенин": "Порто-Ново",
  "Болгария": "София",

  "Боливия": "Ла-Пас",
  "Босния и Герцеговина": "Сараево",
  "Ботсвана": "Габороне",
  "Бразилия": "Бразилиа",
  "Бруней": "Бандар-Сери-Бегаван",
  "Буркина-Фасо": "Уагадугу",
  "Бурунди": "Бужумбура",
  "Бутан": "Тхимпху",
  "Вануату": "Порт-Вила",
  "Великобритания": "Лондон",
  "Венгрия": "Будапешт",
  "Венесуэла": "Каракас",
  "Восточный Тимор": "Дили",
  "Вьетнам": "Ханой",
  "Габон": "Либревиль",
  "Гаити": "Порт-о-Пренс",
  "Гайана": "Джорджтаун",
  "Гамбия": "Банжул",
  "Гана": "Аккра",

  "Гватемала": "Гватемала",
  "Гвинея": "Конакри",
  "Гвинея-Бисау": "Бисау",
  "Германия": "Берлин",
  "Гондурас": "Тегусигальпа",
  "Гренада": "Сент-Джорджес",
  "Греция": "Афины",
  "Грузия": "Тбилиси",
  "Дания": "Копенгаген",
  "Демократическая Республика Конго": "Киншаса",
  "Джибути": "Джибути",
  "Доминика": "Розо",
  "Доминиканская Республика": "Санто-Доминго",
  "Египет": "Каир",
  "Замбия": "Лусака",
  "Зимбабве": "Хараре",
  "Израиль": "Иерусалим",
  "Индия": "Нью-Дели",
  "Индонезия": "Джакарта",
  "Иордания": "Амман",
  "Ирак": "Багдад",
  "Ирландия": "Дублин",

  "Исландия": "Рейкьявик",
  "Испания": "Мадрид",
  "Италия": "Рим",
  "Йемен": "Сана",
  "Кабо-Верде": "Прая",
  "Казахстан": "Нур-Султан",
  "Камбоджа": "Пномпень",
  "Камерун": "Яунде",
  "Канада": "Оттава",
  "Катар": "Доха",
  "Кения": "Найроби",
  "Киргизия": "Бишкек",
  "Китай": "Пекин",
  "Колумбия": "Богота",
  "Коморы": "Морони",
  "Коста-Рика": "Сан-Хосе",
  "Кот-д’Ивуар": "Ямусукро",
  "Куба": "Гавана",
  "Кувейт": "Эль-Кувейт",
  "Лаос": "Вьентьян",
  "Латвия": "Рига",
  "Ливия": "Триполи",
  "Литва": "Вильнюс",

  "Люксембург": "Люксембург",
  "Маврикий": "Порт-Луи",
  "Мавритания": "Нуакшот",
  "Мадагаскар": "Антананариву",
  "Македония": "Скопье",
  "Малайзия": "Куала-Лумпур",
  "Мали": "Бамако",
  "Мальдивы": "Мале",
  "Мальта": "Валлетта",
  "Марокко": "Рабат",
  "Мексика": "Мехико",
  "Мозамбик": "Мапуту",
  "Молдавия": "Кишинёв",
  "Монако": "Монако",
  "Монголия": "Улан-Батор",
  "Мьянма": "Найпьидо",
  "Намибия": "Виндхук",
  "Нигер": "Ниамей",
  "Нигерия": "Абуджа",
  "Нидерланды": "Амстердам",
  "Никарагуа": "Манагуа",
  "Новая Зеландия": "Веллингтон",
  "Норвегия": "Осло",

  "Объединенные Арабские Эмираты": "Абу-Даби",
  "Оман": "Маскат",
  "Пакистан": "Исламабад",
  "Палау": "Нгерулмуд",
  "Панама": "Панама",
  "Папуа — Новая Гвинея": "Порт-Морсби",
  "Парагвай": "Асунсьон",
  "Перу": "Лима",
  "Польша": "Варшава",
  "Португалия": "Лиссабон",
  "Республика Кипр": "Никосия",
  "Республика Конго": "Браззавиль",
  "Республика Корея": "Сеул",
  "Республика Косово": "Приштина",
  "Россия": "Москва",
  "Руанда": "Кигали",
  "Румыния": "Бухарест",
  "США": "Вашингтон",
  "Сальвадор": "Сан-Сальвадор",
  "Самоа": "Апиа",
  "Сан-Марино": "Сан-Марино",
  "Сан-Томе и Принсипи": "Сан-Томе",
  "Саудовская Аравия": "Эр-Рияд",
  "Свазиленд": "Мбабане",
  "Северная Корея": "Пхеньян",
  "Сейшельские Острова": "Виктория",

  "Сенегал": "Дакар",
  "Сент-Винсент и Гренадины": "Кингстаун",
  "Сент-Китс и Невис": "Бастер",
  "Сент-Люсия": "Кастри",
  "Сербия": "Белград",
  "Сингапур": "Сингапур",
  "Сирия": "Дамаск",
  "Словакия": "Братислава",
  "Словения": "Любляна",
  "Соломоновы Острова": "Хониара",
  "Сомали": "Могадишо",
  "Судан": "Хартум",
  "Суринам": "Парамарибо",
  "Сьерра-Леоне": "Фритаун",
  "Таджикистан": "Душанбе",
  "Таиланд": "Бангкок",
  "Танзания": "Додома",
  "Того": "Ломе",
  "Тонга": "Нукуалофа",

  "Тринидад и Тобаго": "Порт-оф-Спейн",
  "Тунис": "Тунис",
  "Туркменистан": "Ашхабад",
  "Турция": "Анкара",
  "Уганда": "Кампала",
  "Узбекистан": "Ташкент",
  "Украина": "Киев",
  "Уругвай": "Монтевидео",
  "Федеративные Штаты Микронезии": "Паликир",
  "Фиджи": "Сува",
  "Филиппины": "Манила",
  "Финляндия": "Хельсинки",
  "Франция": "Париж",
  "Хорватия": "Загреб",

  "Центральноафриканская Республика": "Банги",
  "Чад": "Загреб",
  "Черногория": "Банги",
  "Чехия": "Прага",
  "Чили": "Сантьяго",
  "Швейцария": "Берн",
  "Швеция": "Стокгольм",
  "Шри-Ланка": "Шри-Джаяварденепура-Котте",
  "Эквадор": "Кито",
  "Экваториальная Гвинея": "Малабо",
  "Эритрея": "Асмэра",
  "Эстония": "Таллин",
  "Эфиопия": "Аддис-Абеба",
  "Южно-Африканская Республика": "Претория",
  "Южный Судан": "Джуба",
  "Ямайка": "Кингстон",
  "Япония": "Токио",
  "Палестина": "Иерусалим"
]
}


var idd = [
  "Australia": "Canberra",
  "Andorra": "Andorra la Vella",
  "Austria": "Vienna",
  "Azerbaijan": "Baku",
  "Albania": "Tirana",
  "Algeria": "Algiers",
  "Angola": "Luanda",
  "Argentina": "Buenos Aires",
  "Armenia": "Yerevan",
  "Afghanistan": "Kabul",
  "Bahamas": "Nassau",
  "Bangladesh": "Dhaka",
  "Barbados": "Bridgetown",
  "Bahrain": "Manama",
  "Belize": "Belmopan",
  "Belarus": "Minsk",
  "Belgium": "Brussels",
  "Benin": "Porto-Novo",
  "Bulgaria": "Sofia",

  "Bolivia": "La Paz",
  "Bosnia and Herzegovina": "Sarajevo",
  "Botswana": "Gaborone",
  "Brazil": "Brasília",
  "Brunei": "Bandar Seri Begawan",
  "Burkina Faso": "Ouagadougou",
  "Burundi": "Bujumbura",
  "Bhutan": "Thimphu",
  "Vanuatu": "Port Vila",
  "United Kingdom": "London",
  "Hungary": "Budapest",
  "Venezuela": "Caracas",
  "East Timor": "Dili",
  "Vietnam": "Hanoi",
  "Gabon": "Libreville",
  "Haiti": "Port-au-Prince",
  "Guyana": "Georgetown",
  "Gambia": "Banjul",
  "Ghana": "Accra",

  "Guatemala": "Guatemala City",
  "Guinea": "Conakry",
  "Guinea-Bissau": "Bissau",
  "Germany": "Berlin",
  "Honduras": "Tegucigalpa",
  "Grenada": "St. George's",
  "Greece": "Athens",
  "Georgia": "Tbilisi",
  "Denmark": "Copenhagen",
  "Democratic Republic of the Congo": "Kinshasa",
  "Djibouti": "Djibouti",
  "Dominica": "Roseau",
  "Dominican Republic": "Santo Domingo",
  "Egypt": "Cairo",
  "Zambia": "Lusaka",
  "Zimbabwe": "Harare",
  "Israel": "Jerusalem",
  "India": "New Delhi",
  "Indonesia": "Jakarta",
  "Jordan": "Amman",
  "Iraq": "Baghdad",
  "Ireland": "Dublin",

  "Iceland": "Reykjavik",
  "Spain": "Madrid",
  "Italy": "Rome",
  "Yemen": "Sana'a",
  "Cape Verde": "Praia",
  "Kazakhstan": "Nur-Sultan",
  "Cambodia": "Phnom Penh",
  "Cameroon": "Yaounde",
  "Canada": "Ottawa",
  "Qatar": "Doha",
  "Kenya": "Nairobi",
  "Kyrgyzstan": "Bishkek",
  "China": "Beijing",
  "Colombia": "Bogotá",
  "Comoros": "Moroni",
  "Costa Rica": "San Jose",
  "Ivory Coast": "Yamoussoukro",
  "Cuba": "Havana",
  "Kuwait": "Kuwait City",
  "Laos": "Vientiane",
  "Latvia": "Riga",
  "Libya": "Tripoli",
  "Lithuania": "Vilnius",

  "Luxembourg": "Luxembourg City",
  "Mauritius": "Port Louis",
  "Mauritania": "Nouakchott",
  "Madagascar": "Antananarivo",
  "North Macedonia": "Skopje",
  "Malaysia": "Kuala Lumpur",
  "Mali": "Bamako",
  "Maldives": "Male",
  "Malta": "Valletta",
  "Morocco": "Rabat",
  "Mexico": "Mexico City",
  "Mozambique": "Maputo",
  "Moldova": "Chisinau",
  "Monaco": "Monaco",
  "Mongolia": "Ulaanbaatar",
  "Myanmar": "Naypyidaw",
  "Namibia": "Windhoek",
  "Niger": "Niamey",
  "Nigeria": "Abuja",
  "Netherlands": "Amsterdam",
  "Nicaragua": "Managua",
  "New Zealand": "Wellington",
  "Norway": "Oslo",

  "United Arab Emirates": "Abu Dhabi",
  "Oman": "Muscat",
  "Pakistan": "Islamabad",
  "Palau": "Ngerulmud",
  "Panama": "Panama City",
  "Papua New Guinea": "Port Moresby",
  "Paraguay": "Asuncion",
  "Peru": "Lima",
  "Poland": "Warsaw",
  "Portugal": "Lisbon",
  "Cyprus": "Nicosia",
  "Republic of the Congo": "Brazzaville",
  "South Korea": "Seoul",
  "Republic of Kosovo": "Pristina",
  "Russia": "Moscow",
  "Rwanda": "Kigali",
  "Romania": "Bucharest",
  "United States of America": "Washington, D.C.",
  "El Salvador": "San Salvador",
  "Samoa": "Apia",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "São Tomé",
  "Saudi Arabia": "Riyadh",
  "Eswatini": "Mbabane",
  "North Korea": "Pyongyang",
  "Seychelles": "Victoria",

  "Senegal": "Dakar",
  "Saint Vincent and the Grenadines": "Kingstown",
  "Saint Kitts and Nevis": "Basseterre",
  "Saint Lucia": "Castries",
  "Serbia": "Belgrade",
  "Singapore": "Singapore",
  "Syria": "Damascus",
  "Slovakia": "Bratislava",
  "Slovenia": "Ljubljana",
  "Solomon Islands": "Honiara",
  "Somalia": "Mogadishu",
  "Sudan": "Khartoum",
  "Suriname": "Paramaribo",
  "Sierra Leone": "Freetown",
  "Tajikistan": "Dushanbe",
  "Thailand": "Bangkok",
  "Tanzania": "Dodoma",
  "Togo": "Lome",
  "Tonga": "Nuku'alofa",

  "Trinidad and Tobago": "Port of Spain",
  "Tunisia": "Tunis",
  "Turkmenistan": "Ashgabat",
  "Turkey": "Ankara",
  "Uganda": "Kampala",
  "Uzbekistan": "Tashkent",
  "Ukraine": "Kyiv",
  "Uruguay": "Montevideo",
  "Federated States of Micronesia": "Palikir",
  "Fiji": "Suva",
  "Philippines": "Manila",
  "Finland": "Helsinki",
  "France": "Paris",
  "Croatia": "Zagreb",

  "Central African Republic": "Bangui",
  "Chad": "N'Djamena",
  "Montenegro": "Podgorica",
  "Czech Republic": "Prague",
  "Chile": "Santiago",
  "Switzerland": "Bern",
  "Sweden": "Stockholm",
  "Sri Lanka": "Sri Jayawardenapura Kotte",
  "Ecuador": "Quito",
  "Equatorial Guinea": "Malabo",
  "Eritrea": "Asmara",
  "Estonia": "Tallinn",
  "Ethiopia": "Addis Ababa",
  "South Africa": "Pretoria",
  "South Sudan": "Juba",
  "Jamaica": "Kingston",
  "Japan": "Tokyo",
  "Palestine": "Jerusalem"

]
