//
//  DataManager.swift
//  4Games
//
//  Created by user on 01.04.2023.
//

import SwiftUI

struct FlagNames {
  let name: String
  let image: String
}


class Flags {

  var flagArray: [FlagNames] = [
    FlagNames(name: NSLocalizedString("Flag of Australia", comment: ""), image: "Флаг Австралии"),
    FlagNames(name: NSLocalizedString("Flag of Australia", comment: ""), image: "Флаг Австралии"),
    FlagNames(name: NSLocalizedString("Flag of Andorra", comment: ""), image: "Флаг Андорры"),
    FlagNames(name: NSLocalizedString("Flag of Austria", comment: ""), image: "Флаг Австрии"),
    FlagNames(name: NSLocalizedString("Flag of Azerbaijan", comment: ""), image: "Флаг Азербайджана"),
    FlagNames(name: NSLocalizedString("Flag of Albania", comment: ""), image: "Флаг Албании"),
    FlagNames(name: NSLocalizedString("Flag of Algeria", comment: ""), image: "Флаг Алжира"),
    FlagNames(name: NSLocalizedString("Flag of Angola", comment: ""), image: "Флаг Анголы"),
    FlagNames(name: NSLocalizedString("Flag of Argentina", comment: ""), image: "Флаг Аргентины"),
    FlagNames(name: NSLocalizedString("Flag of Andorra", comment: ""), image: "Флаг Андорры"),
    FlagNames(name: NSLocalizedString("Flag of Armenia", comment: ""), image: "Флаг Армении"),
    FlagNames(name: NSLocalizedString("Flag of Afghanistan", comment: ""), image: "Флаг Афганистана"),
    FlagNames(name: NSLocalizedString("Flag of the Bahamas", comment: ""), image: "Флаг Багамских Островов"),
    FlagNames(name: NSLocalizedString("Flag of Bangladesh", comment: ""), image: "Флаг Бангладеш"),
    FlagNames(name: NSLocalizedString("Flag of Barbados", comment: ""), image: "Флаг Барбадоса"),
    FlagNames(name: NSLocalizedString("Flag of Bahrain", comment: ""), image: "Флаг Бахрейна"),
    FlagNames(name: NSLocalizedString("Flag of Belize", comment: ""), image: "Флаг Белиза"),
    FlagNames(name: NSLocalizedString("Flag of Belarus", comment: ""), image: "Флаг Белоруссии"),
    FlagNames(name: NSLocalizedString("Flag of Belgium", comment: ""), image: "Флаг Бельгии"),
    FlagNames(name: NSLocalizedString("Flag of Benin", comment: ""), image: "Флаг Бенина"),
    FlagNames(name: NSLocalizedString("Flag of Bulgaria", comment: ""), image: "Флаг Болгарии"),
    FlagNames(name: NSLocalizedString("Flag of Bolivia", comment: ""), image: "Флаг Боливии"),
    FlagNames(name: NSLocalizedString("Flag of Bosnia and Herzegovina", comment: ""), image: "Флаг Боснии и Герцеговины"),

    FlagNames(name: "Флаг Ботсваны", image: "Флаг Ботсваны"),
    FlagNames(name: "Флаг Бразилии", image: "Флаг Бразилии"),
    FlagNames(name: "Флаг Брунеи", image: "Флаг Брунеи"),
    FlagNames(name: "Флаг Буркина-Фасо", image: "Флаг Буркина-Фасо"),
    FlagNames(name: "Флаг Бурунди", image: "Флаг Бурунди"),
    FlagNames(name: "Флаг Бутана", image: "Флаг Бутана"),
    FlagNames(name: "Флаг Вануату", image: "Флаг Вануату"),
    FlagNames(name: "Флаг Великобритании", image: "Флаг Великобритании"),
    FlagNames(name: "Флаг Венгрии", image: "Флаг Венгрии"),
    FlagNames(name: "Флаг Венесуэлы", image: "Флаг Венесуэлы"),
    FlagNames(name: "Флаг Восточного Тимора", image: "Флаг Восточного Тимора"),
    FlagNames(name: "Флаг Вьетнама", image: "Флаг Вьетнама"),
    FlagNames(name: "Флаг Габона", image: "Флаг Габона"),
    FlagNames(name: "Флаг Гаити", image: "Флаг Гаити"),
    FlagNames(name: "Флаг Гамбии", image: "Флаг Гамбии"),
    FlagNames(name: "Флаг Ганы", image: "Флаг Ганы"),
    FlagNames(name: "Флаг Гватемалы", image: "Флаг Гватемалы"),
    FlagNames(name: "Флаг Гвинеи", image: "Флаг Гвинеи"),
    FlagNames(name: "Флаг Гвинеи-Бисау", image: "Флаг Гвинеи-Бисау"),
    FlagNames(name: "Флаг Германии", image: "Флаг Германии"),
    FlagNames(name: "Флаг Гондураса", image: "Флаг Гондураса"),
    FlagNames(name: "Флаг Гренады", image: "Флаг Гренады"),
    FlagNames(name: "Флаг Греции", image: "Флаг Греции"),
    FlagNames(name: "Флаг Грузии", image: "Флаг Грузии"),
    FlagNames(name: "Флаг Дании", image: "Флаг Дании"),
    FlagNames(name: "Флаг Республики Конго", image: "Флаг Республики Конго"),
    FlagNames(name: "Флаг Египта", image: "Флаг Египта"),
    FlagNames(name: "Флаг Замбии", image: "Флаг Замбии"),
    FlagNames(name: "Флаг Зимбабве", image: "Флаг Зимбабве"),
    FlagNames(name: "Флаг Израиля", image: "Флаг Израиля"),
    FlagNames(name: "Флаг Индии", image: "Флаг Индии"),
    FlagNames(name: "Флаг Индонезии", image: "Флаг Индонезии"),
    FlagNames(name: "Флаг Иордании", image: "Флаг Иордании"),
    FlagNames(name: "Флаг Ирака", image: "Флаг Ирака"),
    FlagNames(name: "Флаг Ирландии", image: "Флаг Ирландии"),
    FlagNames(name: "Флаг Исландии", image: "Флаг Исландии"),
    FlagNames(name: "Флаг Испании", image: "Флаг Испании"),
    FlagNames(name: "Флаг Италии", image: "Флаг Италии"),
    FlagNames(name: "Флаг Йемена", image: "Флаг Йемена"),
    FlagNames(name: "Флаг Кабо-Верде", image: "Флаг Кабо-Верде"),
    FlagNames(name: "Флаг Казахстана", image: "Флаг Казахстана"),
    FlagNames(name: "Флаг Камбоджи", image: "Флаг Камбоджи"),
    FlagNames(name: "Флаг Камеруна", image: "Флаг Камеруна"),
    FlagNames(name: "Флаг Канады", image: "Флаг Канады"),
    FlagNames(name: "Флаг Катара", image: "Флаг Катара"),
    FlagNames(name: "Флаг Кении", image: "Флаг Кении"),
    FlagNames(name: "Флаг Киргизии", image: "Флаг Киргизии"),
    FlagNames(name: "Флаг Китая", image: "Флаг Китая"),
    FlagNames(name: "Флаг Колумбии", image: "Флаг Колумбии"),
    FlagNames(name: "Флаг Комор", image: "Флаг Комор"),
    FlagNames(name: "Флаг Коста-Рики", image: "Флаг Коста-Рики"),
    FlagNames(name: "Флаг Кот-д’Ивуара", image: "Флаг Кот-д’Ивуара"),
    FlagNames(name: "Флаг Кубы", image: "Флаг Кубы"),
    FlagNames(name: "Флаг Кувейта", image: "Флаг Кувейта"),
    FlagNames(name: "Флаг Лаоса", image: "Флаг Лаоса"),
    FlagNames(name: "Флаг Латвии", image: "Флаг Латвии"),
    FlagNames(name: "Флаг Ливии", image: "Флаг Ливии"),
    FlagNames(name: "Флаг Литвы", image: "Флаг Литвы"),
    FlagNames(name: "Флаг Люксембурга", image: "Флаг Люксембурга"),
    FlagNames(name: "Флаг Маврикия", image: "Флаг Маврикия"),
    FlagNames(name: "Флаг Мавритании", image: "Флаг Мавритании"),
    FlagNames(name: "Флаг Мадагаскара", image: "Флаг Мадагаскара"),
    FlagNames(name: "Флаг Македонии", image: "Флаг Македонии"),
    FlagNames(name: "Флаг Малайзии", image: "Флаг Малайзии"),
    FlagNames(name: "Флаг Мали", image: "Флаг Мали"),
    FlagNames(name: "Флаг Мальдив", image: "Флаг Мальдив"),
    FlagNames(name: "Флаг Мальты", image: "Флаг Мальты"),
    FlagNames(name: "Флаг Марокко", image: "Флаг Марокко"),
    FlagNames(name: "Флаг Мексики", image: "Флаг Мексики"),
    FlagNames(name: "Флаг Мозамбика", image: "Флаг Мозамбика"),
    FlagNames(name: "Флаг Молдавии", image: "Флаг Молдавии"),
    FlagNames(name: "Флаг Монако", image: "Флаг Монако"),
    FlagNames(name: "Флаг Монголии", image: "Флаг Монголии"),
    FlagNames(name: "Флаг Мьянмы", image: "Флаг Мьянмы"),
    FlagNames(name: "Флаг Намибии", image: "Флаг Намибии"),
    FlagNames(name: "Флаг Нигерии", image: "Флаг Нигерии"),
    FlagNames(name: "Флаг Нидерландов", image: "Флаг Нидерландов"),
    FlagNames(name: "Флаг Никарагуа", image: "Флаг Никарагуа"),
    FlagNames(name: "Флаг Новой Зеландии", image: "Флаг Новой Зеландии"),
    FlagNames(name: "Флаг Норвегии", image: "Флаг Норвегии"),
    FlagNames(name: "Флаг Объединённых Арабских Эмиратов", image: "Флаг Объединённых Арабских Эмиратов"),
    FlagNames(name: "Флаг Омана", image: "Флаг Омана"),
    FlagNames(name: "Флаг Пакистана", image: "Флаг Пакистана"),
    FlagNames(name: "Флаг Панамы", image: "Флаг Панамы"),
    FlagNames(name: "Флаг Папуа — Новой Гвинеи", image: "Флаг Папуа — Новой Гвинеи"),
    FlagNames(name: "Флаг Парагвая", image: "Флаг Парагвая"),
    FlagNames(name: "Флаг Перу", image: "Флаг Перу"),
    FlagNames(name: "Флаг Польши", image: "Флаг Польши"),
    FlagNames(name: "Флаг Португалии", image: "Флаг Португалии"),
    FlagNames(name: "Флаг Республики Кипр", image: "Флаг Республики Кипр"),
    FlagNames(name: "Флаг Республики Конго", image: "Флаг Республики Конго"),
    FlagNames(name: "Флаг Республики Корея", image: "Флаг Республики Корея"),
    FlagNames(name: "Флаг Республики Косово", image: "Флаг Республики Косово"),
    FlagNames(name: "Флаг России", image: "Флаг России"),
    FlagNames(name: "Флаг Руанды", image: "Флаг Руанды"),
    FlagNames(name: "Флаг Румынии", image: "Флаг Румынии"),
    FlagNames(name: "Флаг Сальвадора", image: "Флаг Сальвадора"),
    FlagNames(name: "Флаг Самоа", image: "Флаг Самоа"),
    FlagNames(name: "Флаг Сан-Марино", image: "Флаг Сан-Марино"),
    FlagNames(name: "Флаг Саудовской Аравии", image: "Флаг Саудовской Аравии"),
    FlagNames(name: "Флаг Сейшельских Островов", image: "Флаг Сейшельских Островов"),
    FlagNames(name: "Флаг Сенегала", image: "Флаг Сенегала"),
    FlagNames(name: "Флаг Сербии", image: "Флаг Сербии"),
    FlagNames(name: "Флаг Сингапура", image: "Флаг Сингапура"),
    FlagNames(name: "Флаг Сирии", image: "Флаг Сирии"),
    FlagNames(name: "Флаг Словакии", image: "Флаг Словакии"),
    FlagNames(name: "Флаг Словении", image: "Флаг Словении"),
    FlagNames(name: "Флаг Соединённых Штатов Америки", image: "Флаг Соединённых Штатов Америки"),
    FlagNames(name: "Флаг Соломоновых Островов", image: "Флаг Соломоновых Островов"),
    FlagNames(name: "Флаг Сомали", image: "Флаг Сомали"),
    FlagNames(name: "Флаг Судана", image: "Флаг Судана"),
    FlagNames(name: "Флаг Суринама", image: "Флаг Суринама"),
    FlagNames(name: "Флаг Сьерра-Леоне", image: "Флаг Сьерра-Леоне"),
    FlagNames(name: "Флаг Таджикистана", image: "Флаг Таджикистана"),
    FlagNames(name: "Флаг Таиланда", image: "Флаг Таиланда"),
    FlagNames(name: "Флаг Танзании", image: "Флаг Танзании"),
    FlagNames(name: "Флаг Тонга", image: "Флаг Тонга"),
    FlagNames(name: "Флаг Тринидада и Тобаго", image: "Флаг Тринидада и Тобаго"),
    FlagNames(name: "Флаг Туниса", image: "Флаг Туниса"),
    FlagNames(name: "Флаг Туркмении", image: "Флаг Туркмении"),
    FlagNames(name: "Флаг Турции", image: "Флаг Турции"),
    FlagNames(name: "Флаг Уганды", image: "Флаг Уганды"),
    FlagNames(name: "Флаг Узбекистана", image: "Флаг Узбекистана"),
    FlagNames(name: "Флаг Украины", image: "Флаг Украины"),
    FlagNames(name: "Флаг Уругвая", image: "Флаг Уругвая"),
    FlagNames(name: "Флаг Федеративных Штатов Микронезии", image: "Флаг Федеративных Штатов Микронезии"),
    FlagNames(name: "Флаг Фиджи", image: "Флаг Фиджи"),
    FlagNames(name: "Флаг Филиппин", image: "Флаг Филиппин"),
    FlagNames(name: "Флаг Финляндии", image: "Флаг Финляндии"),
    FlagNames(name: "Флаг Франции", image: "Флаг Франции"),
    FlagNames(name: "Флаг Хорватии", image: "Флаг Хорватии"),
    FlagNames(name: "Флаг Островов Кука", image: "Флаг Островов Кука"),
    FlagNames(name: "Флаг Чада", image: "Флаг Чада"),
    FlagNames(name: "Флаг Черногории", image: "Флаг Черногории"),
    FlagNames(name: "Флаг Чехии", image: "Флаг Чехии"),
    FlagNames(name: "Флаг Чили", image: "Флаг Чили"),
    FlagNames(name: "Флаг Швейцарии", image: "Флаг Швейцарии"),
    FlagNames(name: "Флаг Швеции", image: "Флаг Швеции"),
    FlagNames(name: "Флаг Шри-Ланки", image: "Флаг Шри-Ланки"),
    FlagNames(name: "Флаг Эквадора", image: "Флаг Эквадора"),
    FlagNames(name: "Флаг Экваториальной Гвинеи", image: "Флаг Экваториальной Гвинеи"),
    FlagNames(name: "Флаг Эритреи", image: "Флаг Эритреи"),
    FlagNames(name: "Флаг Эстонии", image: "Флаг Эстонии"),
    FlagNames(name: "Флаг Эфиопии", image: "Флаг Эфиопии"),
    FlagNames(name: "Флаг Южно-Африканской Республики", image: "Флаг Южно-Африканской Республики"),
    FlagNames(name: "Флаг Южного Судана", image: "Флаг Южного Судана"),
    FlagNames(name: "Флаг Ямайки", image: "Флаг Ямайки"),
    FlagNames(name: "Флаг Японии", image: "Флаг Японии"),
    FlagNames(name: "Палестинский флаг", image: "Палестинский флаг")

  ].shuffled()

  var fl = ["Флаг Брунея","Флаг Буркина-Фасо","Флаг Бурунди","Флаг Бутана","Флаг Вануату","Флаг Великобритании","Флаг Венгрии","Флаг Венесуэлы","Флаг Восточного Тимора","Флаг Вьетнама","Флаг Габона","Флаг Гаити","Флаг Гамбии","Флаг Ганы","Флаг Гватемалы","Флаг Гвинеи","Флаг Гвинеи-Бисау","Флаг Германии","Флаг Гондураса","Флаг Гренады","Флаг Греции","Флаг Грузии","Флаг Дании","Флаг Республики Конго","Флаг Египта","Флаг Замбии","Флаг Зимбабве","Флаг Израиля","Флаг Индии","Флаг Индонезии","Флаг Иордании","Флаг Ирака","Флаг Ирландии","Флаг Исландии","Флаг Испании","Флаг Италии","Флаг Йемена","Флаг Кабо-Верде","Флаг Казахстана","Флаг Камбоджи","Флаг Камеруна","Флаг Канады","Флаг Катара","Флаг Кении","Флаг Киргизии","Флаг Китая","Флаг Колумбии","Флаг Комор","Флаг Коста-Рики","Флаг Кот-д’Ивуара","Флаг Кубы","Флаг Кувейта","Флаг Лаоса","Флаг Латвии","Флаг Ливии","Флаг Литвы","Флаг Люксембурга","Флаг Маврикия","Флаг Мавритании","Флаг Мадагаскара","Флаг Македонии","Флаг Малайзии","Флаг Мали","Флаг Мальдив","Флаг Мальты","Флаг Марокко","Флаг Мексики","Флаг Мозамбика","Флаг Молдавии","Флаг Монако","Флаг Монголии","Флаг Мьянмы","Флаг Намибии","Флаг Нигерии","Флаг Нидерландов","Флаг Никарагуа","Флаг Новой Зеландии","Флаг Норвегии", "Флаг Объединённых Арабских Эмиратов","Флаг Омана","Флаг Пакистана","Флаг Панамы","Флаг Папуа — Новой Гвинеи","Флаг Парагвая","Флаг Перу","Флаг Польши","Флаг Португалии","Флаг Республики Кипр","Флаг Республики Конго","Флаг Республики Корея","Флаг Республики Косово","Флаг России","Флаг Руанды","Флаг Румынии","Флаг Сальвадора","Флаг Самоа","Флаг Сан-Марино","Флаг Саудовской Аравии","Флаг Сейшельских Островов","Флаг Сенегала","Флаг Сербии","Флаг Сингапура","Флаг Сирии","Флаг Словакии","Флаг Словении","Флаг Соединённых Штатов Америки","Флаг Соломоновых Островов","Флаг Сомали","Флаг Судана","Флаг Суринама","Флаг Сьерра-Леоне","Флаг Таджикистана","Флаг Таиланда","Флаг Танзании","Флаг Тонга","Флаг Тринидада и Тобаго","Флаг Туниса","Флаг Туркмении","Флаг Турции","Флаг Уганды","Флаг Узбекистана","Флаг Украины","Флаг Уругвая","Флаг Федеративных Штатов Микронезии","Флаг Фиджи","Флаг Филиппин","Флаг Финляндии","Флаг Франции","Флаг Хорватии","Флаг Островов Кука","Флаг Чада","Флаг Черногории","Флаг Чехии","Флаг Чили","Флаг Швейцарии","Флаг Швеции","Флаг Шри-Ланки","Флаг Эквадора","Флаг Экваториальной Гвинеи","Флаг Эритреи","Флаг Эстонии","Флаг Эфиопии","Флаг Южно-Африканской Республики","Флаг Южного Судана","Флаг Ямайки","Флаг Японии","Палестинский флаг"]

}



